name: Continuous Deployment

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: https://mreaacr.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername }}
          password: ${{ secrets.AzureAppService_ContainerPassword }}
      
      - name: Create env file
        run: |
          echo "${{ secrets.MY_ENV_VARIABLES }}" >> .env

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: mreaacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/storyverse:${{ github.ref_name }}
          file: Dockerfile.backend
          build-args: MODE=production

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "storyverse"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          images: "mreaacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/storyverse:${{ github.ref_name }}"

      - name: Clean up registry on failure
        if: failure()
        run: |
          docker rmi mreaacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/storyverse:${{ github.ref_name }} || true